### PR TITLE
Add excludePaths attribute for global and rules config

### PR DESCRIPTION
**Pull request by websolete**
Add excludePaths attribute to allow path exclusions in both global config and for individual rules.
- excludePaths in .codechecker.json will prevent processing of those files whose paths contain one of the strings provided.
- excludePaths in rule definitions will cause the rule to not fire for those files whose paths contain one of the strings provided.

### CODE REVIEW

**Comment by bdw429s** [comment]
Hi @websolete and thanks for the pull request.  Here's some feedback:

* Regarding the new exclude paths at the rule level, I'd like to not go through and add that to all the existing rule JSON files.  I've been wanting to go and strip out all the unused keys for a while, it's just too much cruft.  The core service should default appropriately and validate required keys. 
* What format is excludePaths at the rule level in?  I would prefer for it to be a fileGlobbing pattern so it can be specified as *.cfc, etc.  
* I also think it's a little odd that we have an exclude paths but not an include paths.  We do have the list of file extensions, but I'm thinking perhaps that should be deprecated in favor of a file glob list of includes.  So `"extensions" : "cfm.cfc"` would turn into `"paths" : "**.cf?"`.  That would be more consistent and allow for better configurability, such as a rule that only applied to a single file in a particular folder.  Plus file globbing lets you specify a file in the root or any sub dir.
* Regarding the exclude paths for the entire scan-- the core code checker service doesn't actually employ any filtering on the files right now, it just scans what you give it.  The path filtering was implemented up a level in the CommandBox Command.  Partially because CommandBox already had the fileglobbing module and it was easier to track progress with the progress bar and whatnot if the command controlled the files being processed.  So that said, the top level exclude logic should be added here where the include logic is implemented: 
https://github.com/commandbox-modules/commandbox-codechecker/blob/master/commands/codechecker/run.cfc#L70-L95
You can see we loop over each included path and use the built in globber utility to produce at array of matching file which we loop over to append to a distinct array of files to process.  
* Note, that the includes path is a file globbing path which allows for *, **, and ? placeholders just like bash or Git ignores do.  I believe what you had implemented was just a simple "contains" check.  Here's an overview of what the Globbing library supports:
https://github.com/Ortus-Solutions/globber/blob/master/models/PathPatternMatcher.cfc#L10-L26
* Now, all that said-- I didn't originally intend to build it this way.  Check out these tickets I put in a few weeks back while thinking about this where I wanted to actually just enhance the inbuilt file globber library in CommandBox to support both an array of glob patterns as well as exclude patterns.  
https://ortussolutions.atlassian.net/browse/COMMANDBOX-885
https://ortussolutions.atlassian.net/browse/COMMANDBOX-886
If possible, I'd like to put the work into enhancing the core globbing lib to support this.  The only big drawback there is the globber is a module that ships with CommandBox so it means this feature wouldn't work unless users were on the latest version of CommandBox that had the latest globbing library.  
* Hmm, actually reviewing the code again, I forgot we already have this method 
https://github.com/Ortus-Solutions/globber/blob/master/models/PathPatternMatcher.cfc#L110
That will match a file path against an array of glob patterns and allows exclude patterns already with `!` at the start (like git ignore does)!  That's just what we need.  I think we can refactor the globber DSL to use this instead behind the scenes.  And to make the codechecker work in the meantime, we could replace the Globber DSL in the `codechecker run` command with a cfdirectory and direct use of the pathPatternMatcher class. 
* And finally, you have two new rules that made it into this pull.  Not sure if that was on purpose or not. They seem fine so no need to remove them.

**Comment by lmajano** [comment]
This now has conflits and stale, how do you want to approach it @bdw429s

**Comment by bdw429s** [comment]
Well, my feedback never received any replies and that was a year ago so I guess close this for now.

**Comment by bdw429s** [comment]
These two tickets are now complete and will be in the next version of CommandBox.


https://ortussolutions.atlassian.net/browse/COMMANDBOX-885
https://ortussolutions.atlassian.net/browse/COMMANDBOX-886

This paves the way for better native support of file globbing include and excludes in the CLI commands.

**Pull request closed without merging**
